workflows:
  ios-release:
    name: ajjabestel

    max_build_duration: 120

    environment:
      node: 20
      xcode: latest
      cocoapods: default

      ios_signing:
        distribution_type: development
        bundle_identifier: com.ajjafoodnl.order

    scripts:
      - name: Install Quasar CLI
        script: npm install -g @quasar/cli

      - name: Install dependencies
        script: npm install

      - name: Build Quasar
        script: quasar build -m capacitor -T ios

      - name: Install Pods
        script: |
          cd src-capacitor/ios/App
          pod install
          cd ../../..

      - name: Apply signing
        script: xcode-project use-profiles

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace src-capacitor/ios/App/App.xcworkspace \
            --scheme App

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
